### PR TITLE
updated gh-pages demos

### PR DESCRIPTION
**Pull request by weiserhei**
updated the hosted examples to current DomEvents and linkify and updated three.js library to r75

### CODE REVIEW

**Comment by Ohar** [comment]
@weiserhei Here are conflicts …

**Comment by jeromeetienne** [comment]
is that my last merge ?

**Comment by weiserhei** [comment]
No, this PR was created before your last merge from master.

**Comment by jeromeetienne** [comment]
@weiserhei hey, how is it going ? are the conflicts coming from my last merge. or were they here before ?

**Comment by jeromeetienne** [comment]
oh! This is updating gh-pages ?

gh-pages is only a copy of master, i dont understand. can you explain why you want to update gh-pages

**Comment by jeromeetienne** [comment]
i just made sure gh-pages is in sync with master.

**Comment by weiserhei** [comment]
Yeah, all good now :+1: I just noticed the demos linked from the readme were still running on r71, thats what this PR were for.

**Pull request closed without merging**
